---
title: "Make_combat_figures"
author: "Sophie"
date: "07/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(rstatix)
library(ggpubr)
library(officer)
#library(ggprism)
```


```{r}
#load fpr data for cross-sectional data
vol_cx <- read.csv("Data/fp_vol.csv")
vol_cx$Metric <- "Volume"
corthick_cx <- read.csv("Data/fp_corthick.csv")
corthick_cx$Metric <- "Corthick"
md_cx <- read.csv("Data/fp_md.csv")
md_cx$Metric <- "MD"
fa_cx <- read.csv("Data/fp_fa.csv")
fa_cx$Metric <- "FA"
all_cx <- rbind(vol_cx, corthick_cx, md_cx, fa_cx)
all_cx$Data <- "Cross-sectional data, intercept"


#load fpr data for longitudinal data - intercept
vol_fi <- read.csv("Data/fu_fp_vol.csv")
vol_fi$Metric <- "Volume"
corthick_fi <- read.csv("Data/fu_fp_corthick.csv")
corthick_fi$Metric <- "Corthick"
md_fi <- read.csv("Data/fu_fp_md.csv")
md_fi$Metric <- "MD"
fa_fi <- read.csv("Data/fu_fp_fa.csv")
fa_fi$Metric <- "FA"
all_fi <- rbind(vol_fi, corthick_fi, md_fi, fa_fi)
all_fi$Data <- "Longitudinal data, intercept"

#load fpr data for longitudinal data - slope
vol_fs <- read.csv("Data/fu_fp_vol_slope.csv")
vol_fs$Metric <- "Volume"
corthick_fs <- read.csv("Data/fu_fp_corthick_slope.csv")
corthick_fs$Metric <- "Corthick"
md_fs <- read.csv("Data/fu_fp_md_slope.csv")
md_fs$Metric <- "MD"
fa_fs <- read.csv("Data/fu_fp_fa_slope.csv")
fa_fs$Metric <- "FA"
all_fs <- rbind(vol_fs, corthick_fs, md_fs, fa_fs)
all_fs$Data <- "Longitudinal data, slope"


```


```{r}
#combine all
fp <- rbind(all_cx, all_fi, all_fs)
fp <- fp %>% select(-X)
fp$Method <- factor(fp$Method, levels = c("unharm", "crosscombat", "longcombat", "gamcombat"))
fp$Metric <- factor(fp$Metric, levels = c("Volume", "Corthick", "MD", "FA"))
fp$Data <- factor(fp$Data, levels = c("Cross-sectional data, intercept", "Longitudinal data, intercept","Longitudinal data, slope"))
fp$FPR <- fp$FPR/10
```


```{r}
#Use Friedman test to decide if unharmonized, neuroCombat harmonized and longCombat harmonized data
#generate different false positive rates
#and plot results

stat.test <- fp %>%
  group_by(Metric, Data)%>%
  friedman_test(FPR ~ Method | ROI) %>%
  adjust_pvalue(method = "holm") %>%
  add_significance("p.adj") %>%
  select(Metric, Data, p.adj, p.adj.signif)


dat_text <- fp %>% group_by(Data, Method, Metric) %>% slice(1)
dat_text <- dat_text %>% select(-c(ROI, FPR))
dat_text <- merge(dat_text, stat.test, by = c("Data", "Metric"), all.x = TRUE, all.y = TRUE)
dat_text$p.adj.signif <- gsub("ns", " ", dat_text$p.adj.signif)
dat_text$Label <- paste0("p=", format(round(dat_text$p.adj, 3), nsmall = 3), dat_text$p.adj.signif)


fpr_plot <-
  ggplot(data = fp, aes(x = Method, y = FPR, fill = Method)) +
  geom_hline(yintercept = 5, linetype = "dotted")+
  geom_boxplot() +
  facet_grid(Metric ~ Data) +
  theme_bw()+
 geom_text(
    size    = 3,
    data    = dat_text,
    mapping = aes(x = -Inf, y = Inf, label = Label),
    hjust   = -0.1,
    vjust   = 1.5
  ) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.position = "bottom",
        strip.background = element_rect(fill="grey95"))  +
  labs(y = "False positive rate (%)") + 
  scale_fill_manual(name = "Harmonization method",
                      labels = c("none", "neuroCombat", "longCombat", "gamCombat"),
                    values = c("white", "chartreuse4", "burlywood4", "cadetblue3")) 

ggsave(plot = fpr_plot, 
       filename = "Figures/fpr_plot.tiff",
       width = 19, height = 12, dpi = 300,
       units = "cm")
```




```{r}
#do any of the FPR exceed the accepted significance level of 5%

df_p_val <- fp %>%
  group_by(Metric, Data, Method)%>%
  wilcox_test(data =., FPR ~ 1, 
              mu = 5, alternative = "greater") 
df_p_val$Padj <- p.adjust(df_p_val$p)


```







